### ISSUE TITLE
Looking up a word in the second Tab 

### ISSUE THREAD

**Issue by wow-meow-ai** [dahu/vimdictive#1]
Dear Barry,

Many thanks for the outstanding and super handy vim plugin! Until recently, I encounter an issue when editing markdown file.

#### Error Description

Everything runs well in **buffers** in the first tab. But when I activate _vimdictive_ in the second **Tab**. The following error prompts:

```
    Error detected while processing function PreviewTerm:
    line    5:
    E121: Undefined variable: t:term_stack
    E116: Invalid arguments for function add
```

#### Environment

NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=
2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE
-D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LE
VEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes
-std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=aut
o -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
-I/build/neovim-HJnLxJ/neovim-0.2.2/build/config
-I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr
/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include
-I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src
/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Thank you in advance!

**Comment by dahu** [comment]
I'll have a look at this tomorrow afternoon.

**Comment by dahu** [comment]
Turns out I found some time to do it sooner.

**Comment by wow-meow-ai** [comment]
Many thanks!
________________________________
发件人: Barry Arthur <notifications@github.com>
发送时间: 2018年2月27日 19:44
收件人: dahu/vimdictive
抄送: Honig; Author
主题: Re: [dahu/vimdictive] Looking up a word in the second Tab (#1)


Turns out I found some time to do it sooner.

―

**Comment by dahu** [comment]
You're welcome
